name: Tonic
options:
  bundleIdPrefix: com.tonic
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm
    from: "5.0.0"
  PostHog:
    url: https://github.com/PostHog/posthog-ios
    from: "3.0.0"

targets:
  Tonic:
    type: application
    platform: iOS
    sources:
      - path: Tonic
        excludes:
          - "Supabase/migrations/**"
          - "Supabase/functions/**"
          - "Resources/**"
          - "Info.plist"
      - path: Tonic/Resources
        buildPhase: resources
    info:
      path: Tonic/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UIApplicationSupportsIndirectInputEvents: true
        UIAppFonts:
          - Geist-Light.ttf
          - Geist-Regular.ttf
          - Geist-Medium.ttf
          - Geist-SemiBold.ttf
          - Geist-Bold.ttf
          - GeistMono-Regular.ttf
          - GeistMono-Medium.ttf
          - GeistPixel-Grid.ttf
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
        UIStatusBarStyle: UIStatusBarStyleDefault
    settings:
      base:
        PRODUCT_NAME: Ample
        PRODUCT_MODULE_NAME: Tonic
        PRODUCT_BUNDLE_IDENTIFIER: com.tonic.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Supabase
        product: Supabase
      - package: RevenueCat
        product: RevenueCat
      - package: PostHog
        product: PostHog

  TonicTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TonicTests
    dependencies:
      - target: Tonic
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Ample.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Ample"
        BUNDLE_LOADER: "$(TEST_HOST)"
